# Generated by Django 5.2.5 on 2026-04-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information_System', '0006_remove_email_from_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemapping',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
